images: ['europe-docker.pkg.dev/$PROJECT_ID/devops/conventional-commits:$TAG_NAME']
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/cloud-builders/git']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=europe-docker.pkg.dev/$PROJECT_ID/devops/conventional-commits:$TAG_NAME', '.']
  #Test sane output
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', '--volume','/workspace:/git', 'europe-docker.pkg.dev/$PROJECT_ID/devops/conventional-commits:$TAG_NAME']
